global using Microsoft.AspNetCore.Mvc;
global using Repositories.Extensions;
global using Services;
global using Services.Extensions;
global using Services.Products;
global using Services.Products.Create;
global using Services.Products.Update;
global using Services.Products.UpdateStock;
global using System.Net;